### ISSUE TITLE
Support messages that are displayed on specific items

### ISSUE THREAD

**Issue by DarKDinDoN** [kaelad02/adv-reminder#17]
Hello,

I think we can easily add the following keys to the message feature:
- flags.adv-reminder.message.attack.${this.itemName}
- flags.adv-reminder.message.damage.${this.itemName}

It would allow us to handle such feat:
_**Pounce**. If the tiger moves at least 20 feet straight toward a creature and then hits it with a claw attack on the same turn, that target must succeed on a DC 13 Strength saving throw or be knocked prone. If the target is prone, the tiger can make one bite attack against it as a bonus action._

The effect on the `Pounce` would then be: `flags.adv-reminder.message.attack.claw` ➡️ `Pounce. Don't you forget this feat while making a claw attack!`

**Comment by kaelad02** [comment]
Doesn't that really belong on the item's description? If it is, then it'll show up in the item chat card.

**Comment by DarKDinDoN** [comment]
I don't see any reason not to implement this, because:
- There is an advantage to this reminder (pun intended). Having an information in a description of an object that does not belong in the raw material to this item kind of hide the information alongside with the rest. The reminder is clear enough so you don't forget
- As stated, in the raw material, the information does not belong to the item description 
- We might not see all the use cases here. Someone else might find this useful
- This is actually a 4 lines modification, without breaking/compatibility risks

**Comment by MaxPat931** [comment]
I do think there is value in this, I would find it useful to add a description to Divine Smite's damage rolls for "Additional 1d8 if the target is a fiend or undead"

There are probably several magic weapons with similar caveats that would have a similar use case (first one I found was Corpse Slayer)

**Comment by kaelad02** [comment]
I still don't see it. The item's description is the main body of the chat card. Shouldn't that be enough? I think some of my hesitation too is coming up with the keys. I think we might have to slugify the item name to make it work, otherwise what would the key look like for a Battleaxe +1?

Instead of new AE keys, what if we supported active effects on the item that don't transfer to the actor? They could use the existing attack and damage keys. So instead of only searching for active effects on the actor and target, we could include non-transferrable one on the item in use.

Is that an okay compromise?

**Comment by cadowtin** [comment]
I think the AE key as originally proposed would be useful

**Comment by MaxPat931** [comment]
`So instead of only searching for active effects on the actor and target, we could include non-transferrable one on the item in use.`
This sounds like an interesting solution, I think that it would satisfy the use case and not "bloat" the flags with another option

**Comment by cadowtin** [comment]
I also like that option as well ^

**Comment by DarKDinDoN** [comment]
This is indeed an interesting option, I agree.
But that doesn't actually cover the initial use-case of that thread. It still forces us to add an item effect that doesn't belong to that item.

If I want to copy-past that item to another PC/NPC I might need to delete that key, cause that character might not have the relevant feat. And if I copy the feat to another character, I might need to add the key to the relevant attack.

I'm not quite comfortable adding things that don't belong to an item.
It doesn't feel like an actual solution to the problem at hand.

**Comment by kaelad02** [comment]
Just reviewing issues and realized if they do foundryvtt/dnd5e#1539 then it'll make this easier
