### ISSUE TITLE
flags.adv-reminder.message.all does not show on attack or damage rolls

### ISSUE THREAD

**Issue by MaxPat931** [kaelad02/adv-reminder#18]
Does work for skill and ability rolls, but not seeing it on weapon or spell attack or damage rolls

![image](https://user-images.githubusercontent.com/86370342/151891596-dda952af-9d16-4762-b066-856fd0e101bc.png)

--
Sorry, this was with Midi enabled, so it's probably just due to the incompatibility there, #16 is probably tracking the relevant info?

**Comment by kaelad02** [comment]
Yeah, nothing I can do here unfortunately. Midi doesn't pass `dialogOptions` through on attack and damage rolls and this module uses that to "tag" the dialog to make sure the message appears on the right one. So the module is setting the option but unless we get Midi to pass it through then the message won't appear.

**Comment by kaelad02** [comment]
Keeping this open though, should probably add this to the readme. At the very least it'll remind me why it doesn't work!

**Comment by kaelad02** [comment]
Closing now that this issue is captured in the compatibility notes section of the readme

**Comment by MaxPat931** [comment]
Is there an open issue in Midi's Git for this?

**Comment by kaelad02** [comment]
> Is there an open issue in Midi's Git for this?

Not that I know of. I didn't file one. Think I should?

**Comment by MaxPat931** [comment]
Midi probably wont change without one, right? It would be a great boon to this mod if it was implemented

**Comment by kaelad02** [comment]
I know I should, but just didn't want to at the time. I think I was just sour on Midi compatibility issues because I wrote this module so I didn't have to use Midi. I'll reopen this and file an issue there. It'll be blocked until/unless Midi fixes it, but we can have this issue as a reminder

**Comment by kaelad02** [comment]
https://gitlab.com/tposney/midi-qol/-/issues/689

**Comment by MaxPat931** [comment]
Looks to be resolved with the latest midi update!
Thanks for creating that ticket, I could not have made one with nearly the same detail
