### ISSUE TITLE
Saving throw advantage flag not working with better rolls for 5e on version 9

### ISSUE THREAD

**Issue by Hokage3211** [kaelad02/adv-reminder#37]
I'm in version 9, and using the better rolls for 5e seems to work great for ability checks, but the saving throw advantage flag doesn't seem to work on saving throws, nor does adding on additional stuff for NPCs, player's saving throws still don't get advantage but their saving throws do display the +0[rage] label I added. Any ideas on how to fix this?

![image](https://user-images.githubusercontent.com/54164358/193985254-b55a1662-fb33-43ca-964d-0bf73c7ca933.png)

![image](https://user-images.githubusercontent.com/54164358/193985451-7731ad5e-0e27-442e-9b53-b3cb16a79b63.png)

**Comment by kaelad02** [comment]
I tested this with the following versions:
- Foundry v9.269
- dnd5e v1.6.3
- Advantage Reminder v2.0.1
- Better Rolls v1.7.2

I can reproduce the issue and have a workaround for you. Both AR and BR are intercepting the saving throw and ability check calls and the order is different between the two. For an ability check AR runs first and will apply advantage/disadvantage. For a saving throw, BR runs first and sets a flag to fast-forward the roll and so AR skips advantage/disadvantage checks. You can change the order by going into libWrapper's settings and prioritize Advantage Reminder so it shows up first.

Open the settings and go to the Module Settings tab. Then scroll down to libWrapper and click the "libWrapper Settings Menu" button. You'll see a bunch of modules in the middle, Unprioritized Packages, section. Select Advantage Reminder and click the Up arrow to move it into the top, Prioritized Packages, section. That will make sure AR runs first and will apply advantage/disadvantage to both ability checks and saving throws. Please confirm that this works for you.

![image](https://user-images.githubusercontent.com/19502084/194048418-59d727c3-aa09-4280-8895-0042ff7d7b41.png)

**Comment by Hokage3211** [comment]
Was that with the "add" mode, and what priority / value? Thank you again!

**Comment by Hokage3211** [comment]
I found my issue, a module had somehow set the bonus to saving throws on my creature to this 
![image](https://user-images.githubusercontent.com/54164358/194116878-410fe44c-5670-4a10-b05b-25dddb4d7405.png)
which is not good, it has to be set to "+0", or left blank. This menu can be accessed when clicking on the cog wheel when you hover over the strength stat on the 5e stat block.
