### ISSUE TITLE
Support Inline Roll Commands in messages

### ISSUE THREAD

**Issue by MaxPat931** [kaelad02/adv-reminder#40]
Using /rollItem in the damage dialog I can create consumables that can add to the current roll, in a slightly roundabout way, using /rollItem to consume the charge of the item, and then the bonus damage in a regular deferred inline roll.
Could also be useful with #38 for example with Sanctuary, grant a reminder on attack rolls that has a [[/rollSave wis]] so the attacker who forgot to roll beforehand gets a prompt to do so

![image](https://user-images.githubusercontent.com/86370342/199802005-7fa75dc7-43b0-4b55-a68b-bf47bc8e246d.png)

**Comment by kaelad02** [comment]
`TextEditor#enrichHTML`, the Foundry function responsible for making the inline rolls and document links doesn't add the custom enrichers, which IRC uses, if you run the function synchronously. Changing it to `async` will get it to use the custom enrichers, gotta test if there's any other side effect considering all this work is done in a hook.

**Comment by kaelad02** [comment]
Gonna add a few more updates, then I'll push a new release that'll include this
