### ISSUE TITLE
Feature: Add advantage reminder on concentration from midi-qol

### ISSUE THREAD

**Issue by Tallon159** [kaelad02/adv-reminder#53]
Hello,
I noticed that the flag 'flags.midi-qol.advantage.concentration' is not supported by advantage reminder. Is it possible to add it?
Thanks

**Comment by kaelad02** [comment]
I didn't originally support it because that's a flag for Midi's implementation of Concentration checks. The system on its own doesn't have concentration checks and if you're using Midi for that then it's handling that flag already.

What module are you using to handle concentration?

**Comment by Tallon159** [comment]
I use Midi to handle concentration but i'm in manual roll. When i use automated roll, the flag is correctly handle by midi but with manual roll, there is no reminder.

**Comment by kaelad02** [comment]
Going over this again, that sounds like a bug with Midi QOL. I took a peek at manual rolls for concentration checks to see if I could add messages to that dialog but it looks like a regular CON saving through. There's nothing passed in the hook I use that reliably identifies it as a concentration check.

I'll check with the other concentration module to see if it does anything like that and see if Midi can do the same.

**Comment by kaelad02** [comment]
I forgot to close this when I released version 4.0.0. It supports the system's concentration and adds message capabilities w/ `flags.adv-reminder.message.ability.concentration`.
