### ISSUE TITLE
Feature: Support for messages on initiative rolls

### ISSUE THREAD

**Issue by Ikaguia** [kaelad02/adv-reminder#55]
Add support for a flag like `flags.adv-reminder.message.init` for showing messages on the initiative roll.

**Comment by kaelad02** [comment]
I would love to interact with the initiative roll but the way they ordered things in the system, it's not possible. Advantage Reminder works by using the system-defined hooks and they did things backwards when it comes to initiative. There is a `dnd5e.preRollInitiative` but it doesn't fire before the dialog for initiative like all the other "pre" hooks do.

**Comment by kaelad02** [comment]
There were a few developers that pointed it out and they weren't gonna change the order. I'll gladly reopen this if we get that changed.
