### ISSUE TITLE
[Bug] Quick roll compatability for Ready Set Roll does not appear to work in DnD 3.03

### ISSUE THREAD

**Issue by LeoHuntsman** [kaelad02/adv-reminder#58]
As mentioned in the title. Quick rolls do not appear to apply the relevant advantage or disadvantage. Using Alt to bring up the regular roll menu does appear make it apply as normal.

![image](https://github.com/kaelad02/adv-reminder/assets/113218754/219a0601-686e-4b04-99e7-f31f8b6e6ee3)

**Comment by kaelad02** [comment]
I was unable to reproduce the issue. I tested with:

- dnd5e v3.0.2
- Advantage Reminder v3.3.0
- Ready Set Roll v3.0.9

**Comment by LeoHuntsman** [comment]
- dnd5e v3.0.**3**
- Advantage Reminder v3.3.0
- Ready Set Roll v3.0.9

**Comment by kaelad02** [comment]
I was testing attacks, which work fine. I tested skill and ability checks and was able to reproduce it. With the refactoring that RSR did, mainly now using the same hooks that AR uses, the order of the code has swapped. Now AR runs its stuff before RSR. I'll see if it's possible to rearrange that to get AR's hooks to fire after RSR's.
