### ISSUE TITLE
[FEATURE] grants advantage depending on distance?

### ISSUE THREAD

**Issue by DarKDinDoN** [kaelad02/adv-reminder#6]
Hello,

The "Prone" condition grants advantage to a melee attack and disadvantage to a distance attack.
Do you think it's doable?

**Comment by kaelad02** [comment]
The tricky part is doing the distance-to-target check. I'm sure it's possible. If I can figure that out, I guess it would be possible but I'd have to define a new key to use it, like `flags.adv-reminder.prone`.

> An attack roll against the creature has advantage if the attacker is within 5 feet of the creature. Otherwise, the attack roll has disadvantage.

DFreds Convenient Effects setup Prone to assume you're getting advantage with melee attacks and disadvantage with ranged attacks. A reasonable assumption to make to simplify things. CUB's version of prone gives disadvantage to all attacks.

I guess the question is: is the extra complexity worth it or are the assumptions CUB and CE make good enough?

**Comment by DarKDinDoN** [comment]
From the two, I think that the "DFreds Convenient Effects" way is the best.
I think you are right, the extra complexity is not worth it. Thx for the thoughs on this!
