### ISSUE TITLE
Damage Enrichers cause an error to be thrown

### ISSUE THREAD

**Issue by etiquettestartshere** [kaelad02/adv-reminder#70]
To reproduce: put a damage enricher like `[[/damage formula=1d4 type=fire]]` in a journal or chat card and then click it. The TypeError  "Cannot read properties of undefined (reading 'actor')" is thrown. Only occurs with Advantage Reminder enabled. Results obtained on Foundry version 11.315 (node.js+chrome), dnd5e 3.1.2, adv-reminder 3.4.1 and 4.0.0, no other modules enabled.

![image](https://github.com/kaelad02/adv-reminder/assets/148253744/98218812-1077-4adb-8942-2c9f35f5b7ea)
![image](https://github.com/kaelad02/adv-reminder/assets/148253744/a1ede653-8d3a-4d5b-9420-f871f0d5e66b)
![image](https://github.com/kaelad02/adv-reminder/assets/148253744/fe5de714-964d-4ce2-b4d7-fae4c3946eef)
![image](https://github.com/kaelad02/adv-reminder/assets/148253744/028662d8-ec14-413f-b600-656c9fbd758d)

**Comment by kaelad02** [comment]
made a new release, version 4.0.1, with this bug fix
