### ISSUE TITLE
[PHB 2024] Barbarian Rage doesn't trigger adv-reminder

### ISSUE THREAD

**Issue by MrCandleguy** [kaelad02/adv-reminder#78]
When the Barbarian is in Rage the following triggers should be available:

- Advantage on all attacks
- Disadvantage on all attacks on the Barb
- Strength saving throws advantage

However, 'Normal' is highlighted for all of these rolls.

**Comment by kaelad02** [comment]
Did you add any of the relevant flags to the active effect the Rage feature has? The PHB only has the stuff on the active effect that the system supports, like damage resistance. It doesn't add things that are left to modules to support, like advantage on strength checks.

**Comment by MrCandleguy** [comment]
Oh - nope I didn't! I'll jack this issue up to user issue!
